"""create raw_events table

Revision ID: cfcf39d204d1
Revises:
Create Date: 2026-04-28 08:27:17.749704

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cfcf39d204d1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_events",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Internal surrogate key.",
        ),
        sa.Column(
            "source",
            sa.Text(),
            nullable=False,
            comment="Origin of the event, e.g. 'ocr_bot', 'manual'.",
        ),
        sa.Column(
            "source_event_id",
            sa.Text(),
            nullable=False,
            comment="Natural ID assigned by the source system.",
        ),
        sa.Column(
            "received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this row was inserted into the warehouse.",
        ),
        sa.Column(
            "occurred_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            comment="When the underlying real-world event happened, if known.",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Verbatim payload from the source.",
        ),
        sa.Column(
            "parsed",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Structured representation produced by the parse step.",
        ),
        sa.Column(
            "parse_status",
            sa.Text(),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="Lifecycle: pending -> ok | failed.",
        ),
        sa.Column(
            "parse_error",
            sa.Text(),
            nullable=True,
            comment="Error message if parse_status = 'failed'.",
        ),
        sa.CheckConstraint(
            "parse_status IN ('pending', 'ok', 'failed')", name="ck_raw_events_parse_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_event_id", name="uq_raw_events_source_natural_key"),
    )
    op.create_index(
        "ix_raw_events_pending",
        "raw_events",
        ["id"],
        unique=False,
        postgresql_where=sa.text("parse_status = 'pending'"),
    )
    op.create_index(
        "ix_raw_events_source_received_at",
        "raw_events",
        ["source", sa.literal_column("received_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_events_source_received_at", table_name="raw_events")
    op.drop_index(
        "ix_raw_events_pending",
        table_name="raw_events",
        postgresql_where=sa.text("parse_status = 'pending'"),
    )
    op.drop_table("raw_events")
    # ### end Alembic commands ###
